---
deployment:
  tasks:
    - export DEPLOYPATH=/home/johncuys/public_html/
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R fonts $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R projects $DEPLOYPATH
    - /bin/cp -R gallery $DEPLOYPATH
    - /bin/cp -R about $DEPLOYPATH
    - /bin/cp -R contact $DEPLOYPATH